[package]
name = "nstack"
version = "0.7.0"
authors = ["Kristoffer Str√∂m <kristoffer@dusk.network>"]
edition = "2018"
description = "Arity 4 stack for the kelvin merkle toolkit"
license = "MPL-2.0"
repository = "https://github.com/dusk-network/nstack"
keywords = ["merkle", "datastructure", "stack"]

[dependencies]
microkelvin = { path = "../microkelvin" }
canonical = "0.6"
canonical_derive = "0.6"
